# Generated by Django 5.1.4 on 2024-12-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_icon', models.ImageField(upload_to='categories/icons/')),
                ('category_image', models.ImageField(upload_to='categories/images/')),
                ('subcategories', models.ManyToManyField(related_name='categories', to='apiApp.subcategory')),
            ],
        ),
    ]
