# Generated by Django 5.1.4 on 2024-12-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(default=dict, help_text="Store product specifications as a dictionary (e.g., {'processor': 'Intel i7', 'ram': '16GB'}). You can add any key-value pairs relevant to the product."),
        ),
    ]
