# Generated by Django 5.1.4 on 2024-12-11 11:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_alter_product_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(default='', help_text="Store product specifications as a dictionary (e.g., {'processor': 'Intel i7', 'ram': '16GB'}). You can add any key-value pairs relevant to the product."),
        ),
    ]
